const data = [
  {
    _id: "6zYpyeZmt6TZNNOxUf7N1",
    name: "Cell Structure and Organisation",
    level: 1,
    parentId: null,
  },
  {
    _id: "eaVlFFzxl1TNG1nLRaVLa",
    name: "Movement of Substances",
    level: 1,
    parentId: null,
  },
  {
    _id: "pdtxImlsBjvmpSnE9hhaW",
    name: "Biological Molecules",
    level: 1,
    parentId: null,
  },
  {
    _id: "tf5W8KLUvSRJsQ1Pzogua",
    name: "Nutrition in Humans",
    level: 1,
    parentId: null,
  },
  {
    _id: "eXDezFxTZT-XqzRJIxqql",
    name: "Nutrition in Plants",
    level: 1,
    parentId: null,
  },
  {
    _id: "5M4qfTDPOgCTJaSwcGciQ",
    name: "Transport in Flowering Plants",
    level: 1,
    parentId: null,
  },
  {
    _id: "URNe5V6lDo4OZ6j99PDZd",
    name: "Transport in Humans",
    level: 1,
    parentId: null,
  },
  {
    _id: "xDfN7sNrELy1tOlo5G_xL",
    name: "Respiration in Humans",
    level: 1,
    parentId: null,
  },
  {
    _id: "HwBUWIVoSov585mi5l_Cc",
    name: "Excretion in Humans",
    level: 1,
    parentId: null,
  },
  {
    _id: "TvYA3PdZJGlYRW346qPti",
    name: "Homeostasis",
    level: 1,
    parentId: null,
  },
  {
    _id: "ttyoQErfLARoG6p28fYxC",
    name: "Co-ordination and Response in Humans",
    level: 1,
    parentId: null,
  },
  {
    _id: "MYxePEKT1G-OP7vBn6jnw",
    name: "Reproduction",
    level: 1,
    parentId: null,
  },
  {
    _id: "zGUb3O1Gymi_QPeM6m-DI",
    name: "Cell Division",
    level: 1,
    parentId: null,
  },
  {
    _id: "lrgz7nPLIgxwSOtvpaJ99",
    name: "Molecular Genetics",
    level: 1,
    parentId: null,
  },
  {
    _id: "DHKWSvCYut6c8i_U_INCo",
    name: "Inheritance",
    level: 1,
    parentId: null,
  },
  {
    _id: "q9C-cBCR0eX0lzw2KmIB4",
    name: "Organisms and their Environment",
    level: 1,
    parentId: null,
  },
  {
    _id: "ECaB5wxReAlFSGjL0cbrZ",
    name: "Identify cell structures (including organelles) of typical plant and animal cells from diagrams, photomicrographs and as seen under the light microscope using prepared slides and fresh material treated with an appropriate temporary staining technique:",
    level: 2,
    parentId: "6zYpyeZmt6TZNNOxUf7N1",
  },
  {
    _id: "fNHYv6gvPfWtvqn4uElwS",
    name: "Identify the following membrane systems and organelles from diagrams and electron micrographs:",
    level: 2,
    parentId: "6zYpyeZmt6TZNNOxUf7N1",
  },
  {
    _id: "sX0TIdVMchoupAxclDbaz",
    name: "State the functions of the membrane systems and organelles identified above",
    level: 2,
    parentId: "6zYpyeZmt6TZNNOxUf7N1",
  },
  {
    _id: "NUz0ECZyI8yvmCWNJ7Eiy",
    name: "Compare the structure of typical animal and plant cells",
    level: 2,
    parentId: "6zYpyeZmt6TZNNOxUf7N1",
  },
  {
    _id: "4K-hecOgiurmyBSwuRcTf",
    name: "State, in simple terms, the relationship between cell function and cell structure for the following:",
    level: 2,
    parentId: "6zYpyeZmt6TZNNOxUf7N1",
  },
  {
    _id: "MKZNBmToar54Yswz1MR4B",
    name: "Differentiate cell, tissue, organ and organ system",
    level: 2,
    parentId: "6zYpyeZmt6TZNNOxUf7N1",
  },
  {
    _id: "E5ZvXtgY--g9EnCLuy6uk",
    name: "Define diffusion and describe its role in nutrient uptake and gaseous exchange in plants and humans",
    level: 2,
    parentId: "eaVlFFzxl1TNG1nLRaVLa",
  },
  {
    _id: "jj9DKAMLQp0Q7tWRUm69s",
    name: "Define osmosis and describe the effects of osmosis on plant and animal tissues",
    level: 2,
    parentId: "eaVlFFzxl1TNG1nLRaVLa",
  },
  {
    _id: "tyDO48n7FQdUt6An5ofOO",
    name: "Define active transport and discuss its importance as an energy-consuming process by which substances are transported against a concentration gradient, as in ion uptake by root hairs and uptake of glucose by cells in the villi",
    level: 2,
    parentId: "eaVlFFzxl1TNG1nLRaVLa",
  },
  {
    _id: "EC-wexyPo0HSlYUAP6-IX",
    name: "State the roles of water in living organisms",
    level: 2,
    parentId: "pdtxImlsBjvmpSnE9hhaW",
  },
  {
    _id: "w7T67HEczzT4nOI2fCSan",
    name: "List the chemical elements which make up",
    level: 2,
    parentId: "pdtxImlsBjvmpSnE9hhaW",
  },
  {
    _id: "pLjUbEPlfXn4oYO8w7ZMV",
    name: "Describe and carry out tests for",
    level: 2,
    parentId: "pdtxImlsBjvmpSnE9hhaW",
  },
  {
    _id: "79lOHnP3IwkdOIOsVDaLl",
    name: "State that large molecules are synthesised from smaller basic units",
    level: 2,
    parentId: "pdtxImlsBjvmpSnE9hhaW",
  },
  {
    _id: "vwBxhPYF0bIQPGnfz7UfK",
    name: "Explain enzyme action in terms of the ‘lock and key’ hypothesis",
    level: 2,
    parentId: "pdtxImlsBjvmpSnE9hhaW",
  },
  {
    _id: "92ZtNYgYTK6gl6nt4IF5k",
    name: "Explain the mode of action of enzymes in terms of an active site, enzyme-substrate complex, lowering of activation energy and enzyme specificity",
    level: 2,
    parentId: "pdtxImlsBjvmpSnE9hhaW",
  },
  {
    _id: "05EFl6dA3YemgFVmuB6X1",
    name: "Investigate and explain the effects of temperature and pH on the rate of enzyme catalysed reactions",
    level: 2,
    parentId: "pdtxImlsBjvmpSnE9hhaW",
  },
  {
    _id: "3NmokEVrtByfUtkqEWFTP",
    name: "Describe the functions of main regions of the alimentary canal and the associated organs: mouth, salivary glands, oesophagus, stomach, duodenum, pancreas, gall bladder, liver, ileum, colon, rectum, anus, in relation to ingestion, digestion, absorption, assimilation and egestion of food, as appropriate",
    level: 2,
    parentId: "tf5W8KLUvSRJsQ1Pzogua",
  },
  {
    _id: "VmGDVVkyFh-98Yn8d5bUk",
    name: "Describe peristalsis in terms of rhythmic wave-like contractions of the muscles to mix and propel the contents of the alimentary canal",
    level: 2,
    parentId: "tf5W8KLUvSRJsQ1Pzogua",
  },
  {
    _id: "s6maotIAvYTsvjuLxNJk5",
    name: "Describe the functions of enzymes (e.g. amylase, maltase, protease, lipase) in digestion, listing the substrates and end-products",
    level: 2,
    parentId: "tf5W8KLUvSRJsQ1Pzogua",
  },
  {
    _id: "OtwYyNphFuw-l_8qI8RCg",
    name: "Describe the structure of a villus and its role, including the role of capillaries and lacteals in absorption",
    level: 2,
    parentId: "tf5W8KLUvSRJsQ1Pzogua",
  },
  {
    _id: "hHFNdQcuIVdYD5O4gIB3Y",
    name: "State the function of the hepatic portal vein as the transport of blood rich in absorbed nutrients from the small intestine to the liver",
    level: 2,
    parentId: "tf5W8KLUvSRJsQ1Pzogua",
  },
  {
    _id: "1PC8VdfM9vyPUiRVSuV-a",
    name: "State the role of the liver in",
    level: 2,
    parentId: "tf5W8KLUvSRJsQ1Pzogua",
  },
  {
    _id: "N9ie6jPcScbwa_UacXtlZ",
    name: "Describe the effects of excessive consumption of alcohol: reduced self-control, depressant, effect on reaction times, damage to liver and social implications",
    level: 2,
    parentId: "tf5W8KLUvSRJsQ1Pzogua",
  },
  {
    _id: "55v2RlQCK_BfYKdJEa1M3",
    name: "Identify and label the cellular and tissue structure of a dicotyledonous leaf, as seen in transverse section using the light microscope and describe the significance of these features in terms of their functions, such as the",
    level: 2,
    parentId: "eXDezFxTZT-XqzRJIxqql",
  },
  {
    _id: "wPUcLhIRUXyhBtaJ9FEfj",
    name: "State the equation, in words and symbols, for photosynthesis",
    level: 2,
    parentId: "eXDezFxTZT-XqzRJIxqql",
  },
  {
    _id: "a3F_9Z8Lzq056ddXNb-qx",
    name: "Describe the intake of carbon dioxide and water by plants",
    level: 2,
    parentId: "eXDezFxTZT-XqzRJIxqql",
  },
  {
    _id: "OGkTt9ngKc3P8bPCPmi95",
    name: "State that chlorophyll traps light energy and converts it into chemical energy for the formation of carbohydrates and their subsequent uses",
    level: 2,
    parentId: "eXDezFxTZT-XqzRJIxqql",
  },
  {
    _id: "Vdv7RoZmLwmkvQIfP72Uu",
    name: "Investigate and discuss the effects of varying light intensity, carbon dioxide concentration and temperature on the rate of photosynthesis (e.g. in submerged aquatic plant)",
    level: 2,
    parentId: "eXDezFxTZT-XqzRJIxqql",
  },
  {
    _id: "aK7IRfUPCAPLEcY3Y25Bd",
    name: "Discuss light intensity, carbon dioxide concentration and temperature as limiting factors on the rate of photosynthesis",
    level: 2,
    parentId: "eXDezFxTZT-XqzRJIxqql",
  },
  {
    _id: "Vo3axYrO1urvm_ipigfZF",
    name: "Identify the positions and explain the functions of xylem vessels, phloem (sieve tube elements and companion cells) in sections of a herbaceous dicotyledonous leaf and stem, using the light microscope",
    level: 2,
    parentId: "5M4qfTDPOgCTJaSwcGciQ",
  },
  {
    _id: "xRU-avIaiAjqC0xS8-1W7",
    name: "Relate the structure and functions of root hairs to their surface area, and to water and ion uptake",
    level: 2,
    parentId: "5M4qfTDPOgCTJaSwcGciQ",
  },
  {
    _id: "fmA1xNlKvD4jbyZaEDwLp",
    name:
      "Explain the movement of water between plant cells, and between them and the environment in\n" +
      "terms of water potential (calculations on water potential are not required)",
    level: 2,
    parentId: "5M4qfTDPOgCTJaSwcGciQ",
  },
  {
    _id: "9y22ixg7RB8H5BykflA0j",
    name: "Outline the pathway by which water is transported from the roots to the leaves through the xylem vessels",
    level: 2,
    parentId: "5M4qfTDPOgCTJaSwcGciQ",
  },
  {
    _id: "6CnHD3lZJ7mlEybxeClhn",
    name: "Define the term transpiration and explain that transpiration is a consequence of gaseous exchange in plants",
    level: 2,
    parentId: "5M4qfTDPOgCTJaSwcGciQ",
  },
  {
    _id: "yZ_an2fAprjNOwRm-ds09",
    name: "Describe and explain",
    level: 2,
    parentId: "5M4qfTDPOgCTJaSwcGciQ",
  },
  {
    _id: "OVSmTj76BUlF7lu_O3Cw8",
    name: "Define the term translocation as the transport of food in the phloem tissue and illustrate the process through translocation studies",
    level: 2,
    parentId: "5M4qfTDPOgCTJaSwcGciQ",
  },
  {
    _id: "Te0mPM6iAgk4t52KE31Pn",
    name: "Identify the main blood vessels to and from the heart, lungs, liver and kidney",
    level: 2,
    parentId: "URNe5V6lDo4OZ6j99PDZd",
  },
  {
    _id: "XsGBUtDyZSZXWztYYAMjx",
    name: "State the role of blood in transport and defence",
    level: 2,
    parentId: "URNe5V6lDo4OZ6j99PDZd",
  },
  {
    _id: "mPhAfXZRHOToSgGP0rVvF",
    name: "List the different ABO blood groups and all possible combinations for the donor and recipient in blood transfusions",
    level: 2,
    parentId: "URNe5V6lDo4OZ6j99PDZd",
  },
  {
    _id: "1mV970TwHu8sOQYSXLYLO",
    name: "Relate the structure of arteries, veins and capillaries to their functions",
    level: 2,
    parentId: "URNe5V6lDo4OZ6j99PDZd",
  },
  {
    _id: "fXeM3mbsjdZaAGVfRiOVX",
    name: "Describe the transfer of materials between capillaries and tissue fluid",
    level: 2,
    parentId: "URNe5V6lDo4OZ6j99PDZd",
  },
  {
    _id: "-6ZsMtgY48XfaB_nQCFi-",
    name: "Describe the structure and function of the heart in terms of muscular contraction and the working of valves",
    level: 2,
    parentId: "URNe5V6lDo4OZ6j99PDZd",
  },
  {
    _id: "KO-wgjnQozmBZ2k6J9jos",
    name: "Outline the cardiac cycle in terms of what happens during systole and diastole (histology of the heart muscle, names of nerves and transmitter substances are not required)",
    level: 2,
    parentId: "URNe5V6lDo4OZ6j99PDZd",
  },
  {
    _id: "tQcoEXd8959zTaoFH0dh7",
    name: "Describe coronary heart disease in terms of the occlusion of coronary arteries and list the possible causes, such as diet, stress and smoking, stating the possible preventative measures",
    level: 2,
    parentId: "URNe5V6lDo4OZ6j99PDZd",
  },
  {
    _id: "C1309BnAI3wF6BPoZ-sca",
    name: "Identify on diagrams and name the larynx, trachea, bronchi, bronchioles, alveoli and associated capillaries",
    level: 2,
    parentId: "xDfN7sNrELy1tOlo5G_xL",
  },
  {
    _id: "W3LXGlxqiKVaRcncKA93C",
    name: "State the characteristics of, and describe the role of, the exchange surface of the alveoli in gas exchange",
    level: 2,
    parentId: "xDfN7sNrELy1tOlo5G_xL",
  },
  {
    _id: "proXHU1iQ7C_elynS5d0E",
    name: "Describe the removal of carbon dioxide from the lungs, including the role of the carbonic anhydrase enzyme",
    level: 2,
    parentId: "xDfN7sNrELy1tOlo5G_xL",
  },
  {
    _id: "YU0gk4hGLL6MePUBMVNfN",
    name: "Describe the role of cilia, diaphragm, ribs and intercostal muscles in breathing",
    level: 2,
    parentId: "xDfN7sNrELy1tOlo5G_xL",
  },
  {
    _id: "kHAtFeFyEs6E8e3eIJW4X",
    name: "Describe the effect of tobacco smoke and its major toxic components – nicotine, tar and carbon monoxide, on health",
    level: 2,
    parentId: "xDfN7sNrELy1tOlo5G_xL",
  },
  {
    _id: "Dzb40GdIA4E_m471cXVks",
    name: "Define and state the equation, in words and symbols, for aerobic respiration in humans",
    level: 2,
    parentId: "xDfN7sNrELy1tOlo5G_xL",
  },
  {
    _id: "Xnop0UWy42hi_zbOXEdbt",
    name: "Define and state the equation, in words only, for anaerobic respiration in humans",
    level: 2,
    parentId: "xDfN7sNrELy1tOlo5G_xL",
  },
  {
    _id: "YM4pQzPECv3QJ2Tz5Y5OC",
    name: "Describe the effect of lactic acid in muscles during exercise",
    level: 2,
    parentId: "xDfN7sNrELy1tOlo5G_xL",
  },
  {
    _id: "SQHc2phlgoeNaPAAPweV_",
    name: "Define excretion and explain the importance of removing nitrogenous and other compounds from the body",
    level: 2,
    parentId: "HwBUWIVoSov585mi5l_Cc",
  },
  {
    _id: "tW5Uy8ZkOA57NjNq0qWY_",
    name: "Outline the function of the nephron with reference to ultra-filtration and selective reabsorption in the production of urine",
    level: 2,
    parentId: "HwBUWIVoSov585mi5l_Cc",
  },
  {
    _id: "t9PGAOHLSnOOe1fJ3Ys8P",
    name: "Outline the role of anti-diuretic hormone (ADH) in osmoregulation",
    level: 2,
    parentId: "HwBUWIVoSov585mi5l_Cc",
  },
  {
    _id: "OexcM28jtyview3JVPoJS",
    name: "Outline the mechanism of dialysis in the case of kidney failure",
    level: 2,
    parentId: "HwBUWIVoSov585mi5l_Cc",
  },
  {
    _id: "cCU67JdrfpOcMuQojJhgO",
    name: "Define homeostasis as the maintenance of a constant internal environment",
    level: 2,
    parentId: "TvYA3PdZJGlYRW346qPti",
  },
  {
    _id: "fyTLiyGELjkL7i1ovZH7J",
    name: "Explain the basic principles of homeostasis in terms of stimulus resulting from a change in the internal environment, a corrective mechanism and negative feedback",
    level: 2,
    parentId: "TvYA3PdZJGlYRW346qPti",
  },
  {
    _id: "5HtgoKITtMFo8_I-P-FQD",
    name: "Identify on a diagram of the skin: hairs, sweat glands, temperature receptors, blood vessels and fatty tissue",
    level: 2,
    parentId: "TvYA3PdZJGlYRW346qPti",
  },
  {
    _id: "SrUYN1H9RsYrVINOoQAX6",
    name: "Describe the maintenance of a constant body temperature in humans in terms of insulation and the role of: temperature receptors in the skin, sweating, shivering, blood vessels near the skin surface and the co-ordinating role of the hypothalamus",
    level: 2,
    parentId: "TvYA3PdZJGlYRW346qPti",
  },
  {
    _id: "mRy_AYlFbIR_yPbQxjH17",
    name: "State the relationship between receptors, the central nervous system and the effectors",
    level: 2,
    parentId: "ttyoQErfLARoG6p28fYxC",
  },
  {
    _id: "-aYYRo1bwyrmMGnTJwimQ",
    name: "Describe the structure of the eye as seen in front view and in horizontal section",
    level: 2,
    parentId: "ttyoQErfLARoG6p28fYxC",
  },
  {
    _id: "tpMAbDm0WnSr6y_ep5-qp",
    name: "State the principal functions of component parts of the eye in producing a focused image of near and distant objects on the retina",
    level: 2,
    parentId: "ttyoQErfLARoG6p28fYxC",
  },
  {
    _id: "pnCW-agDoq1Y5OpQFh5mh",
    name: "Describe the pupil reflex in response to bright and dim light",
    level: 2,
    parentId: "ttyoQErfLARoG6p28fYxC",
  },
  {
    _id: "JcV-8DQeHiCJ4d8meym6d",
    name: "State that the nervous system – brain, spinal cord and nerves, serves to co-ordinate and regulate bodily functions",
    level: 2,
    parentId: "ttyoQErfLARoG6p28fYxC",
  },
  {
    _id: "9Z4kWfwCjWhmozpiHMIy9",
    name: "Outline the functions of sensory neurones, relay neurones and motor neurones",
    level: 2,
    parentId: "ttyoQErfLARoG6p28fYxC",
  },
  {
    _id: "Ke9Rgfyo-wlC05B3Fp4Ds",
    name: "Discuss the function of the brain and spinal cord in producing a co-ordinated response as a result of a specific stimulus in a reflex action",
    level: 2,
    parentId: "ttyoQErfLARoG6p28fYxC",
  },
  {
    _id: "wtvrASsg1FwjnXI62E4RK",
    name: "Define a hormone as a chemical substance, produced by a gland, carried by the blood, which alters the activity of one or more specific target organs and is then destroyed by the liver",
    level: 2,
    parentId: "ttyoQErfLARoG6p28fYxC",
  },
  {
    _id: "7WBmDX-CujpQekcFrbfcD",
    name: "Explain what is meant by an endocrine gland, with reference to the islets of Langerhans in the pancreas",
    level: 2,
    parentId: "ttyoQErfLARoG6p28fYxC",
  },
  {
    _id: "NmbkHPKUDClL1guWWLamN",
    name: "State the role of the hormone adrenaline in boosting blood glucose levels and give examples of situations in which this may occur",
    level: 2,
    parentId: "ttyoQErfLARoG6p28fYxC",
  },
  {
    _id: "vXIpYHq16M9rKsmx5m69S",
    name: "Explain how the blood glucose concentration is regulated by insulin and glucagon as a homeostatic mechanism",
    level: 2,
    parentId: "ttyoQErfLARoG6p28fYxC",
  },
  {
    _id: "vKPNSi7RtQs8R4NGZTuJY",
    name: "Describe the signs, such as an increased blood glucose level and glucose in urine, and the treatment of diabetes mellitus using insulin",
    level: 2,
    parentId: "ttyoQErfLARoG6p28fYxC",
  },
  {
    _id: "Yta-IisZX7nYx0oGml1mE",
    name: "Define asexual reproduction as the process resulting in the production of genetically identical offspring from one parent",
    level: 2,
    parentId: "MYxePEKT1G-OP7vBn6jnw",
  },
  {
    _id: "tNtZazVA2E-GlwMYV09UP",
    name: "Define sexual reproduction as the process involving the fusion of nuclei to form a zygote and the production of genetically dissimilar offspring",
    level: 2,
    parentId: "MYxePEKT1G-OP7vBn6jnw",
  },
  {
    _id: "H7h7DVZ5d9edThJ9qTrPR",
    name: "Identify and draw, using a hand lens if necessary, the sepals, petals, stamens and carpels of one, locally available, named, insect-pollinated, dicotyledonous flower, and examine the pollen grains using a microscope",
    level: 2,
    parentId: "MYxePEKT1G-OP7vBn6jnw",
  },
  {
    _id: "WbCYkqx0PnASgendcPc6i",
    name: "State the functions of the sepals, petals, anthers and carpels",
    level: 2,
    parentId: "MYxePEKT1G-OP7vBn6jnw",
  },
  {
    _id: "3RfttDGT-xfcYMHYlKqn2",
    name: "Use a hand lens to identify and describe the stamens and stigmas of one, locally available, named, wind-pollinated flower, and examine the pollen grains using a microscope",
    level: 2,
    parentId: "MYxePEKT1G-OP7vBn6jnw",
  },
  {
    _id: "3tS_cg6sWz2zuyVBLCckN",
    name: "Outline the process of pollination and distinguish between self-pollination and cross-pollination",
    level: 2,
    parentId: "MYxePEKT1G-OP7vBn6jnw",
  },
  {
    _id: "MBg8Rv0Uze5BLJyokeRRR",
    name: "Compare, using fresh specimens, an insect-pollinated and a wind-pollinated flower",
    level: 2,
    parentId: "MYxePEKT1G-OP7vBn6jnw",
  },
  {
    _id: "HeFt8Y29paUmGPMqCNnAr",
    name: "Describe the growth of the pollen tube and its entry into the ovule followed by fertilisation (production of endosperm and details of development are not required)",
    level: 2,
    parentId: "MYxePEKT1G-OP7vBn6jnw",
  },
  {
    _id: "GR9b9RRoahopmxvbMOAAz",
    name: "Identify on diagrams, the male reproductive system and give the functions of: testes, scrotum, sperm ducts, prostate gland, urethra and penis",
    level: 2,
    parentId: "MYxePEKT1G-OP7vBn6jnw",
  },
  {
    _id: "ENxXb8NOInAx5U8C9zel-",
    name: "Identify on diagrams, the female reproductive system and give the functions of: ovaries, oviducts, uterus, cervix and vagina",
    level: 2,
    parentId: "MYxePEKT1G-OP7vBn6jnw",
  },
  {
    _id: "qin9_6uf02UYnIVLM7SAq",
    name: "Briefly describe the menstrual cycle with reference to the alternation of menstruation and ovulation, the natural variation in its length, and the fertile and infertile phases of the cycle with reference to the effects of progesterone and estrogen only",
    level: 2,
    parentId: "MYxePEKT1G-OP7vBn6jnw",
  },
  {
    _id: "VJtZ2zCGcNJw8kLjq4OZ3",
    name: "Describe fertilisation and early development of the zygote simply in terms of the formation of a ball of cells which becomes implanted in the wall of the uterus",
    level: 2,
    parentId: "MYxePEKT1G-OP7vBn6jnw",
  },
  {
    _id: "WgPNC7Wq0fEFiGAb-jF1n",
    name: "State the functions of the amniotic sac and the amniotic fluid",
    level: 2,
    parentId: "MYxePEKT1G-OP7vBn6jnw",
  },
  {
    _id: "Eq_9emMzXBYFerdzAXHxZ",
    name: "Describe the function of the placenta and umbilical cord in relation to exchange of dissolved nutrients, gases and excretory products (structural details are not required)",
    level: 2,
    parentId: "MYxePEKT1G-OP7vBn6jnw",
  },
  {
    _id: "IVQD9hPVQqHIqFxKAgqDX",
    name: "Discuss the spread of human immunodeficiency virus (HIV) and methods by which it may be controlled",
    level: 2,
    parentId: "MYxePEKT1G-OP7vBn6jnw",
  },
  {
    _id: "Z-Rj7nmZeFBGWnLi3h6tg",
    name: "State the importance of mitosis in growth, repair and asexual reproduction",
    level: 2,
    parentId: "zGUb3O1Gymi_QPeM6m-DI",
  },
  {
    _id: "P0DNyx4CF9bWSUrNDrafB",
    name: "Explain the need for the production of genetically identical cells",
    level: 2,
    parentId: "zGUb3O1Gymi_QPeM6m-DI",
  },
  {
    _id: "bZyzr_qsqcrOK667BEk2l",
    name: "Identify, with the aid of diagrams, the main stages of mitosis",
    level: 2,
    parentId: "zGUb3O1Gymi_QPeM6m-DI",
  },
  {
    _id: "6binerx46lMyexLiu1RHC",
    name: "State what is meant by homologous pairs of chromosomes",
    level: 2,
    parentId: "zGUb3O1Gymi_QPeM6m-DI",
  },
  {
    _id: "v1tfeZe3BzvhLHt0koHlN",
    name: "Identify, with the aid of diagrams, the main stages of meiosis (names of the sub-divisions of prophase are not required)",
    level: 2,
    parentId: "zGUb3O1Gymi_QPeM6m-DI",
  },
  {
    _id: "OXE9Z-bRb1rLl_OFBTIiz",
    name: "Define the terms haploid and diploid, and explain the need for a reduction division process prior to fertilisation in sexual reproduction",
    level: 2,
    parentId: "zGUb3O1Gymi_QPeM6m-DI",
  },
  {
    _id: "DkMCgpG7Irha7Cb1hXUtW",
    name: "State how meiosis and fertilisation can lead to variation",
    level: 2,
    parentId: "zGUb3O1Gymi_QPeM6m-DI",
  },
  {
    _id: "z7yxlgXBIEcl5UC56mvdX",
    name: "Outline the relationship between DNA, genes and chromosomes",
    level: 2,
    parentId: "lrgz7nPLIgxwSOtvpaJ99",
  },
  {
    _id: "8kDx8DUuRzcxUiIH9QeuG",
    name: "State the structure of DNA in terms of the bases, sugar and phosphate groups found in each of their nucleotides",
    level: 2,
    parentId: "lrgz7nPLIgxwSOtvpaJ99",
  },
  {
    _id: "2wg_Mb8nJJwtc07pasoea",
    name: "State the rule of complementary base pairing",
    level: 2,
    parentId: "lrgz7nPLIgxwSOtvpaJ99",
  },
  {
    _id: "DMwKd_DKW3Gm9gqi0pjhm",
    name: "State that DNA is used to carry the genetic code, which is used to synthesise specific polypeptides (details of transcription and translation are not required)",
    level: 2,
    parentId: "lrgz7nPLIgxwSOtvpaJ99",
  },
  {
    _id: "wTypz7Dfg8YP593Jugvz0",
    name: "State that each gene is a sequence of nucleotides, as part of a DNA molecule",
    level: 2,
    parentId: "lrgz7nPLIgxwSOtvpaJ99",
  },
  {
    _id: "DpSmTxe-I-1IeOcAmOevt",
    name: "Explain that genes may be transferred between cells. Reference should be made to the transfer of genes between organisms of the same species or different species – transgenic plants or animals",
    level: 2,
    parentId: "lrgz7nPLIgxwSOtvpaJ99",
  },
  {
    _id: "AxLBvJvn1QuV_DK1wD0fL",
    name: "Briefly explain how a gene that controls the production of human insulin can be inserted into bacterial DNA to produce human insulin in medical biotechnology",
    level: 2,
    parentId: "lrgz7nPLIgxwSOtvpaJ99",
  },
  {
    _id: "IMKkS15MOT2Ue94pf91fe",
    name: "Discuss the social and ethical implications of genetic engineering, with reference to a named example",
    level: 2,
    parentId: "lrgz7nPLIgxwSOtvpaJ99",
  },
  {
    _id: "0WeGk4wcFI2tKsaYNM-2g",
    name: "Define a gene as a unit of inheritance and distinguish clearly between the terms gene and allele",
    level: 2,
    parentId: "DHKWSvCYut6c8i_U_INCo",
  },
  {
    _id: "nGQenGOgKygQpn9ejdqjS",
    name: "Explain the terms dominant, recessive, codominant, homozygous, heterozygous, phenotype and genotype",
    level: 2,
    parentId: "DHKWSvCYut6c8i_U_INCo",
  },
  {
    _id: "n9dE8QcJlXFXhuhvMdvHF",
    name: "Predict the results of simple crosses with expected ratios of 3:1 and 1:1, using the terms homozygous, heterozygous, F1 generation and F2 generation",
    level: 2,
    parentId: "DHKWSvCYut6c8i_U_INCo",
  },
  {
    _id: "DzwvwCvcTe8qe_zx47A-R",
    name: "Explain why observed ratios often differ from expected ratios, especially when there are small numbers of progeny",
    level: 2,
    parentId: "DHKWSvCYut6c8i_U_INCo",
  },
  {
    _id: "2h4KjS1L9OnPu7ftIg1Im",
    name: "Use genetic diagrams to solve problems involving monohybrid inheritance (genetic diagrams involving autosomal linkage or epistasis are not required)",
    level: 2,
    parentId: "DHKWSvCYut6c8i_U_INCo",
  },
  {
    _id: "iXeFkrWlpsxpQ5o9dyEHL",
    name: "Explain co-dominance and multiple alleles with reference to the inheritance of the ABO blood group phenotypes (A, B, AB and O) and the gene alleles (Iᴬ, Iᴮ and Iᴼ)",
    level: 2,
    parentId: "DHKWSvCYut6c8i_U_INCo",
  },
  {
    _id: "D5eEcxjZisR6ve94UmH_C",
    name: "Describe the determination of sex in humans – XX and XY chromosomes",
    level: 2,
    parentId: "DHKWSvCYut6c8i_U_INCo",
  },
  {
    _id: "jZ-jPh0iB2Hs4O7MvKx1d",
    name: "Describe mutation as a change in the structure of a gene such as in sickle cell anaemia, or in the chromosome number, such as the 47 chromosomes in the condition known as Down syndrome",
    level: 2,
    parentId: "DHKWSvCYut6c8i_U_INCo",
  },
  {
    _id: "-I3otRmxv4MfTYy4Akaqz",
    name: "Name radiation and chemicals as factors which may increase the rate of mutation",
    level: 2,
    parentId: "DHKWSvCYut6c8i_U_INCo",
  },
  {
    _id: "IpVCzW3buGezOwXdIIWY2",
    name: "Describe the difference between continuous and discontinuous variation and give examples of each",
    level: 2,
    parentId: "DHKWSvCYut6c8i_U_INCo",
  },
  {
    _id: "0kJtzneM905stFzoT9rYm",
    name: "State that variation and competition lead to differential survival of, and reproduction by, those organisms best fitted to the environment",
    level: 2,
    parentId: "DHKWSvCYut6c8i_U_INCo",
  },
  {
    _id: "7fuPAkJ2PVXfssSO6n53w",
    name: "Give examples of environmental factors that act as forces of natural selection",
    level: 2,
    parentId: "DHKWSvCYut6c8i_U_INCo",
  },
  {
    _id: "oMgIV8Tp713-MjSBF8PF7",
    name: "Explain the role of natural selection as a possible mechanism for evolution",
    level: 2,
    parentId: "DHKWSvCYut6c8i_U_INCo",
  },
  {
    _id: "sJvWQHviUilu-o-w0q7e1",
    name: "Give examples of artificial selection such as in the production of economically important plants and animals",
    level: 2,
    parentId: "DHKWSvCYut6c8i_U_INCo",
  },
  {
    _id: "KRuDUHHFOsDWWgXsxMIpU",
    name: "Briefly describe the non-cyclical nature of energy flow",
    level: 2,
    parentId: "q9C-cBCR0eX0lzw2KmIB4",
  },
  {
    _id: "OT2AviuswmWUgjQHRuWQy",
    name: "Explain the terms producer, consumer and trophic level in the context of food chains and food webs",
    level: 2,
    parentId: "q9C-cBCR0eX0lzw2KmIB4",
  },
  {
    _id: "LFqLHNlRx_WX5tmxlk1dp",
    name: "Explain how energy losses occur along food chains, and discuss the efficiency of energy transfer between trophic levels",
    level: 2,
    parentId: "q9C-cBCR0eX0lzw2KmIB4",
  },
  {
    _id: "F7qKlCYLI3ZG7XB3SL8oc",
    name: "Describe and interpret pyramids of numbers and biomass",
    level: 2,
    parentId: "q9C-cBCR0eX0lzw2KmIB4",
  },
  {
    _id: "T4aZWPeOjUCuQ4ExDYzDp",
    name: "Describe how carbon is cycled within an ecosystem and outline the role of forests and oceans as carbon sinks",
    level: 2,
    parentId: "q9C-cBCR0eX0lzw2KmIB4",
  },
  {
    _id: "tnIaEVVdCl69cTBGeS06D",
    name: "Evaluate the effects of",
    level: 2,
    parentId: "q9C-cBCR0eX0lzw2KmIB4",
  },
  {
    _id: "GMjJg3WNaRGXSsuHs8lso",
    name: "Outline the roles of microorganisms in sewage treatment as an example of environmental biotechnology",
    level: 2,
    parentId: "q9C-cBCR0eX0lzw2KmIB4",
  },
  {
    _id: "Z2SD6rpjoMS4ndrD8_4Ax",
    name: "Discuss reasons for conservation of species with reference to the maintenance of biodiversity and how this is done, e.g. management of fisheries and management of timber production",
    level: 2,
    parentId: "q9C-cBCR0eX0lzw2KmIB4",
  },
  {
    _id: "Be4MsWsncaMMx5up0uiTc",
    name: "Chloroplasts",
    level: 3,
    parentId: "ECaB5wxReAlFSGjL0cbrZ",
  },
  {
    _id: "CwH3Y_SvNWanhFlt8soIq",
    name: "Cell surface membrane",
    level: 3,
    parentId: "ECaB5wxReAlFSGjL0cbrZ",
  },
  {
    _id: "v10Xfnw8EyfVwylHJHr6P",
    name: "Cell wall",
    level: 3,
    parentId: "ECaB5wxReAlFSGjL0cbrZ",
  },
  {
    _id: "hD87EsqPShZrzhCCemQLf",
    name: "Cytoplasm",
    level: 3,
    parentId: "ECaB5wxReAlFSGjL0cbrZ",
  },
  {
    _id: "TQ4fxcFOFVJpKba4B3BLj",
    name: "Cell vacuoles (large, sap-filled in plant cells, small, temporary in animal cells)",
    level: 3,
    parentId: "ECaB5wxReAlFSGjL0cbrZ",
  },
  {
    _id: "2hQkRI-WvOjy8d44DHLyb",
    name: "Nucleus",
    level: 3,
    parentId: "ECaB5wxReAlFSGjL0cbrZ",
  },
  {
    _id: "EN6P59UQ6AG42t1aukGwt",
    name: "Endoplasmic reticulum",
    level: 3,
    parentId: "fNHYv6gvPfWtvqn4uElwS",
  },
  {
    _id: "3U9CYm2-IfRjaDwzoOCa6",
    name: "Mitochondria",
    level: 3,
    parentId: "fNHYv6gvPfWtvqn4uElwS",
  },
  {
    _id: "i8XHbDmwk7YLfg_Hxeydw",
    name: "Golgi body",
    level: 3,
    parentId: "fNHYv6gvPfWtvqn4uElwS",
  },
  {
    _id: "tKHc9at9uaSjPtPBs8LVI",
    name: "Ribosomes",
    level: 3,
    parentId: "fNHYv6gvPfWtvqn4uElwS",
  },
  {
    _id: "IubW9wFNM7VBLkZsbiGTb",
    name: "",
    level: 3,
    parentId: "sX0TIdVMchoupAxclDbaz",
  },
  {
    _id: "7XgMm8C32uHzVmAZRl8Os",
    name: "Absorption – root hair cells",
    level: 3,
    parentId: "4K-hecOgiurmyBSwuRcTf",
  },
  {
    _id: "4UysR8T7ooFkJWXwW-XNy",
    name: "Conduction and support – xylem vessels",
    level: 3,
    parentId: "4K-hecOgiurmyBSwuRcTf",
  },
  {
    _id: "Mn9rGAfTT9B7z8BiP3-dQ",
    name: "Transport of oxygen – red blood cells",
    level: 3,
    parentId: "4K-hecOgiurmyBSwuRcTf",
  },
  {
    _id: "i5wEgqN2Wpv7WD4gwrYUa",
    name: "Carbohydrates",
    level: 3,
    parentId: "w7T67HEczzT4nOI2fCSan",
  },
  {
    _id: "cOclshOXQdHEx7aiDGD8C",
    name: "Fats",
    level: 3,
    parentId: "w7T67HEczzT4nOI2fCSan",
  },
  {
    _id: "EbCCV0xtIgVUxysTou1Up",
    name: "Proteins",
    level: 3,
    parentId: "w7T67HEczzT4nOI2fCSan",
  },
  {
    _id: "AvmTwnPOZ5HkOL3YxwZxx",
    name: "Starch (iodine in potassium iodide solution)",
    level: 3,
    parentId: "pLjUbEPlfXn4oYO8w7ZMV",
  },
  {
    _id: "i6_Ankv7nx2MFTPZY9SUI",
    name: "Reducing sugars (Benedict's solution)",
    level: 3,
    parentId: "pLjUbEPlfXn4oYO8w7ZMV",
  },
  {
    _id: "Wo8W97Lh-hbjaMMuaG9fz",
    name: "Protein (biuret test)",
    level: 3,
    parentId: "pLjUbEPlfXn4oYO8w7ZMV",
  },
  {
    _id: "-ABX2ZFdH3ickaZrWs6TC",
    name: "Fats (ethanol emulsion)",
    level: 3,
    parentId: "pLjUbEPlfXn4oYO8w7ZMV",
  },
  {
    _id: "_10lO6Vnev3pCu7X3aRcY",
    name: "Glycogen from glucose",
    level: 3,
    parentId: "79lOHnP3IwkdOIOsVDaLl",
  },
  {
    _id: "WyezxDxMaByYSt8NgIis9",
    name: "Polypeptides and proteins from amino acids",
    level: 3,
    parentId: "79lOHnP3IwkdOIOsVDaLl",
  },
  {
    _id: "xbfiE5qTe3-velrFHtBVD",
    name: "Lipids such as fats from glycerol and fatty acids",
    level: 3,
    parentId: "79lOHnP3IwkdOIOsVDaLl",
  },
  {
    _id: "8zqqtUrwzABwfi5utZpUB",
    name: "Carbohydrate metabolism",
    level: 3,
    parentId: "1PC8VdfM9vyPUiRVSuV-a",
  },
  {
    _id: "ZTLKxigp6P0W_DENRrm3R",
    name: "Fat digestion",
    level: 3,
    parentId: "1PC8VdfM9vyPUiRVSuV-a",
  },
  {
    _id: "2mW1k38LnNgDygkXNeoiT",
    name: "Breakdown of red blood cells",
    level: 3,
    parentId: "1PC8VdfM9vyPUiRVSuV-a",
  },
  {
    _id: "-IPaedRS5nBYB3NfTH6HU",
    name: "Metabolism of amino acids and the formation of urea",
    level: 3,
    parentId: "1PC8VdfM9vyPUiRVSuV-a",
  },
  {
    _id: "QjwcOD-0ETZt-_1xqISHB",
    name: "Breakdown of alcohol",
    level: 3,
    parentId: "1PC8VdfM9vyPUiRVSuV-a",
  },
  {
    _id: "_99EQmPBYtMWNDnovld5s",
    name: "Distribution of chloroplasts in photosynthesis",
    level: 3,
    parentId: "55v2RlQCK_BfYKdJEa1M3",
  },
  {
    _id: "qYhNJAiQRnKNQ6UWhYSP0",
    name: "Stomata and mesophyll cells in gaseous exchange",
    level: 3,
    parentId: "55v2RlQCK_BfYKdJEa1M3",
  },
  {
    _id: "K6kZQVXdo4TzBhxrdstys",
    name: "Vascular bundles in transport",
    level: 3,
    parentId: "55v2RlQCK_BfYKdJEa1M3",
  },
  {
    _id: "LjEP8Uhi88ESBpy72c359",
    name: "The effects of variation of air movement, temperature, humidity and light intensity on transpiration rate",
    level: 3,
    parentId: "yZ_an2fAprjNOwRm-ds09",
  },
  {
    _id: "2QWw43KA_y91NcmlHyDaH",
    name: "How wilting occurs",
    level: 3,
    parentId: "yZ_an2fAprjNOwRm-ds09",
  },
  {
    _id: "Bgza5KAUZdK5chdLtf6KA",
    name: "Red blood cells – haemoglobin and oxygen transport",
    level: 3,
    parentId: "XsGBUtDyZSZXWztYYAMjx",
  },
  {
    _id: "wzKgPB_DzTKnZmZKGScdn",
    name: "Plasma – transport of blood cells, ions, soluble food substances, hormones, carbon dioxide, urea, vitamins, plasma proteins",
    level: 3,
    parentId: "XsGBUtDyZSZXWztYYAMjx",
  },
  {
    _id: "HuYZY2lLW87Osozpwl5xd",
    name: "White blood cells – phagocytosis, antibody formation and tissue rejection",
    level: 3,
    parentId: "XsGBUtDyZSZXWztYYAMjx",
  },
  {
    _id: "DPV4PEka_M_bKLwIEwodY",
    name: "Platelets – fibrinogen to fibrin, causing clotting",
    level: 3,
    parentId: "XsGBUtDyZSZXWztYYAMjx",
  },
  {
    _id: "eSzPSeWN5aS_TY9S4_N4p",
    name: "Water pollution by sewage and by inorganic waste",
    level: 3,
    parentId: "tnIaEVVdCl69cTBGeS06D",
  },
  {
    _id: "-zoTaU0MdK_mtH4ybXMnL",
    name: "Pollution due to insecticides including bioaccumulation up food chains and impact on top carnivores",
    level: 3,
    parentId: "tnIaEVVdCl69cTBGeS06D",
  },
];


export default data;